### ISSUE TITLE
Update the Bonjour page for Feb 1 client event

### ISSUE THREAD

**Issue by zarkonite** [jansensan/megapode-website#49]

**Comment by jansensan** [comment]
@zarkonite This seems more like a milestone (or sprint) than an issue. You might want to read about those:

- [About Milestones](https://help.github.com/articles/about-milestones/)
- [Associating milestones with issues and pull requests](https://help.github.com/articles/associating-milestones-with-issues-and-pull-requests/)

In the meantime, should this issue be closed?
